

export enum ACTIONS_TYPE {
    CHANGE_DISPLAY_VALUE = 'CHANGE_DISPLAY_VALUE',
    CHANGE_DISPLAY_ERROR = 'CHANGE_DISPLAY_ERROR',
    CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE',
    CHANGE_INPUT_VALUE_ERROR = 'CHANGE_INPUT_VALUE_ERROR',
    CHANGE_DISABLED_BUTTON = 'CHANGE_DISABLED_BUTTON'
}
